remote_theme: MicrosoftLearning/Jekyll-Theme
exclude:
  - readme.md
  - .github/
  - Instructions/Demos/
  - Instructions/oldLabs/
  - Instructions/Labs/LAB_20-4-C-ExploratoryAnalysisInR.md
  
header_pages:
  - index.html
author: M Mallow
twitter_username: NetKnow
github_username:  MarMall
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

theme: jekyll-theme-slate